services:
  front-end:
    build:
      context: Front
    ports:
      - "5173:5173"
    container_name: front-end
    command: npm run start

  back-end:
    build:
      context: server
    container_name: back-end
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/hidegram
      NODE_ENV: production
    ports:
      - "3000:3000"
      - "5555:5555"
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    container_name: postgres
    restart: always
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hidegram
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    expose:
      - '5433'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d hidegram" ]
      interval: 10s
      timeout: 5s
      retries: 5