FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
#RUN npm run build
#
#FROM node:18-alpine AS production
#
#WORKDIR /app
#
#COPY package*.json ./
#RUN npm install --omit=dev
#
#COPY --from=builder /app/dist ./dist
#COPY --from=builder /app/prisma ./prisma
#COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

# TODO check Expose the application port
#EXPOSE 3000
EXPOSE 3001
#EXPOSE 5555
EXPOSE 5556
