version: '3.9'
services:
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    expose:
      - '5433'
volumes:
  postgres:
