export const fakeChats = [
	{
		id: 1,
		name: "Mark",
		lastMessage: "I don´t know who you are...",
		unreadMessages: 3,
		date: "3:44 pm",
	},
	{
		id: 2,
		name: "Hidegram",
		lastMessage: "Hidegram web was updated",
		unreadMessages: 1,
		date: "3:44 pm",
	},
	{
		id: 3,
		name: "Alice",
		lastMessage: "Why?",
		unreadMessages: 19,
		date: "3:44 pm",
	},
	{
		id: 4,
		name: "Saved Messages",
		lastMessage: "image.jpeg",
		unreadMessages: 3,
		date: "Mon",
	},
	{
		id: 5,
		name: "Mark",
		lastMessage: "I don´t know who you are...",
		unreadMessages: 3,
		date: "3:44 pm",
	},
	{
		id: 6,
		name: "Hidegram",
		lastMessage: "Hidegram web was updated",
		unreadMessages: 1,
		date: "3:44 pm",
	},
	{
		id: 7,
		name: "Alice",
		lastMessage: "Why?",
		unreadMessages: 19,
		date: "3:44 pm",
	},
	{
		id: 8,
		name: "Saved Messages",
		lastMessage: "image.jpeg",
		unreadMessages: 3,
		date: "Mon",
	},
	{
		id: 9,
		name: "Mark",
		lastMessage: "I don´t know who you are...",
		unreadMessages: 3,
		date: "3:44 pm",
	},
	{
		id: 10,
		name: "Hidegram",
		lastMessage: "Hidegram web was updated",
		unreadMessages: 1,
		date: "3:44 pm",
	},
	{
		id: 11,
		name: "Alice",
		lastMessage: "Why?",
		unreadMessages: 19,
		date: "3:44 pm",
	},
	{
		id: 12,
		name: "Saved Messages",
		lastMessage: "image.jpeg",
		unreadMessages: 3,
		date: "Mon",
	},
];

export const fakeMessages = [
	{
		id: "1",
		type: "text",
		content: { text: "Hey, how's it going?" },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T12:30:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "2",
		type: "text",
		content: { text: "Hi. I'm fine." },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T12:35:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "3",
		type: "text",
		content: { text: "Hello, Alice!" },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T12:40:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "4",
		type: "text",
		content: { text: "Hey Bob, how are you?" },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T12:45:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "5",
		type: "text",
		content: { text: "I'm doing great, thanks!" },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T12:50:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "6",
		type: "text",
		content: { text: "That's awesome to hear!" },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T12:55:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "7",
		type: "text",
		content: { text: "How was your day?" },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T13:00:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "8",
		type: "text",
		content: { text: "It was pretty good. What about yours?" },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T13:05:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "9",
		type: "text",
		content: { text: "Mine was busy, but good overall." },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T13:10:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "10",
		type: "text",
		content: { text: "Glad to hear it!" },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T13:15:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "11",
		type: "text",
		content: { text: "What are you up to?" },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T13:20:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "13",
		type: "text",
		content: {
			text: "Sounds nice. Anything exciting planned for the weekend?",
		},
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T13:25:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "133",
		type: "text",
		content: {
			text: "Test three in a row",
		},
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T13:25:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "14",
		type: "text",
		content: { text: "Not really, just some errands." },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T13:30:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "15",
		type: "text",
		content: { text: "That sounds relaxing." },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T13:35:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "16",
		type: "text",
		content: { text: "Yeah, it should be nice." },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T13:40:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "17",
		type: "text",
		content: { text: "I hope the weather stays good." },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T13:45:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "18",
		type: "text",
		content: { text: "Me too. It'll be perfect for a hike." },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T13:50:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "19",
		type: "text",
		content: { text: "That sounds like a great plan." },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T13:55:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "20",
		type: "text",
		content: { text: "Yeah, I'm looking forward to it." },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T14:00:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "21",
		type: "text",
		content: { text: "Well, I better get going. Talk to you later!" },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T14:05:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "22",
		type: "text",
		content: { text: "Okay, take care!" },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T14:10:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "22",
		type: "text",
		content: { text: "Okay, take care! asd qwerty" },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T14:10:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "23",
		type: "text",
		content: { text: "Bye!" },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T14:15:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "24",
		type: "text",
		content: { text: "Goodbye!" },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T14:20:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "25",
		type: "text",
		content: { text: "See you!" },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T14:25:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "36",
		type: "text",
		content: {
			text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		},
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T15:20:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "252",
		type: "image",
		content: { url: "/image-example-3.webp" },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T14:25:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "37",
		type: "text",
		content: {
			text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
		},
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T15:25:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "26",
		type: "file",
		content: {
			icon: "/pdf-file.svg",
			title: "Hidegram GmBh File (1),(2)",
			description: "PDF Document · 4.5 MB",
		},
		sender: { id: "user1", name: "Bob" },
		timestamp: "2022-03-15T12:40:00Z",
		status: "read",
		isRead: true,
	},
	{
		id: "262",
		type: "file",
		content: {
			icon: "/pdf-file.svg",
			title: "Hidegram GmBh File (1),(2)",
			description: "PDF Document · 4.5 MB",
		},
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T12:40:00Z",
		status: "read",
		isRead: true,
	},
	{
		id: "27",
		type: "file",
		content: {
			icon: "/pdf-file.svg",
			title: "Hidegram GmBh File (1),(2)",
			description: "PDF Document · 4.5 MB",
		},
		sender: { id: "user1", name: "Bob" },
		timestamp: "2022-03-15T12:40:00Z",
		status: "read",
		isRead: true,
	},
	{
		id: "28",
		type: "image",
		content: { url: "/image-example.png" },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T12:45:00Z",
		status: "sent",
		isRead: false,
	},
	{
		id: "288",
		type: "image",
		content: { url: "/image-example.png" },
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T12:45:00Z",
		status: "sent",
		isRead: false,
	},
	{
		id: "29",
		type: "image",
		content: { url: "/image-2.jpg" },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T12:50:00Z",
		status: "delivered",
		isRead: true,
	},
	{
		id: "30",
		type: "text",
		content: { text: "Hello" },
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T14:25:00Z",
		status: "sent",
		isRead: true,
	},
].reverse();

export const myData = [
	{ title: "J Black", id: String(Math.random()).slice(8) },
	{ title: "Wife 2", id: String(Math.random()).slice(8) },
	{ title: "Note 12", id: String(Math.random()).slice(8) },
	{ title: "Margus", id: String(Math.random()).slice(8) },
	{ title: "Ketamin pro", id: String(Math.random()).slice(8) },
	{ title: "Wife", id: String(Math.random()).slice(8) },
	{ title: "Kitten", id: String(Math.random()).slice(8) },
	{ title: "Warum nicht", id: String(Math.random()).slice(8) },
	{ title: "Wife 2", id: String(Math.random()).slice(8) },
];
